### ISSUE TITLE
Dag refreshing gardiner dashboard app fails

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_traffic_dashboard#70]
Partial airflow log
```
[2019-12-30 07:35:30,669] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmplsl1xq_k/reload_gunicornpy0mdv3a
[2019-12-30 07:35:30,670] {bash_operator.py:115} INFO - Running command: killall 'gunicorn: master [gardiner]' -HUP
[2019-12-30 07:35:30,674] {bash_operator.py:124} INFO - Output:
[2019-12-30 07:35:30,680] {bash_operator.py:128} INFO - gunicorn: master [gardiner]: no process found
[2019-12-30 07:35:30,680] {bash_operator.py:132} INFO - Command exited with return code 1
[2019-12-30 07:35:30,712] {taskinstance.py:1051} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.5/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.5/site-packages/airflow/operators/bash_operator.py", line 136, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-12-30 07:35:30,713] {taskinstance.py:1082} INFO - Marking task as FAILED.
```

the issue was the dashboard wasn't actually running. Realized per #55, we probably still need a service to run the app so that the app will restart automatically if, for example, the EC2 is restarted. I ran the dashboard by 

```bash
cd /web/gardiner/bdit_traffic_dashboard
pipenv shell
GUNICORN_CMD_ARGS="--bind=0.0.0.0:8055 --log-level debug --timeout 30 --name=gardiner --reload" nohup gunicorn app:server >> app.log &
```

Note the use of `nohup`

**Comment by radumas** [comment]
I also had to recreate the `pipenv` so that `airflow` would be able to run the `gunicorn` process, and there was then an issue that `setproctitle` wasn't installed, so the process wasn't being named correctly, in order to get `setproctitle` to install, I did have to unpin the requirements of the Dash packages because of a conflict with `dash-bootstrap-component = "*"`, so now I'm worried the appearance is a little different...

**Comment by radumas** [comment]
I think the refreshing of the data could be better accomplished within the Dash app. This doesn't solve the issue of the app not appearing to start successfully if the EC2 gets restarted
https://dash.plot.ly/performance
https://dash.plot.ly/live-updates
